server:
  port: 8002

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: 12345678
  dbname: health_dt
  sslmode: disable

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

mqtt:
  broker: "tcp://39.100.101.252:1883"
  client_id: "health_dt_client"
  username: ""
  password: ""

websocket:
  host: "0.0.0.0"
  port: 8765
  path: "/ws/health"

jwt_secret: "your-secret-key"
